Run bower install on the docker build
2ec0b4/kaamelott-soundboard pull request #128
Opened 2019-11-12 20:38 UTC by djerfy

2019-11-12 22:27 UTC, 2ec0b4 requested changes

2019-11-12 22:27 UTC, 2ec0b4 commented on README.md
> -Pour faire fonctionner le projet sur votre machine, vous devrez tout d'abord, depuis la racine, exécuter la commande `bower install` puis accéder au fichier `index.html` via le serveur Web de votre c
J'aurais laissé cette phrase, je pense que l'utilisation de Docker peut rester optionnel. Du coup, à la phrase d'après, peut-être mettre "Ou alors, vous pouvez utiliser Docker"... etc

2019-11-12 22:28 UTC, 2ec0b4 commented
👋
Merci pour cette modification. J'ai mis un petit commentaire sur le README 😊

2019-11-12 23:46 UTC, djerfy commented on README.md
> -Pour faire fonctionner le projet sur votre machine, vous devrez tout d'abord, depuis la racine, exécuter la commande `bower install` puis accéder au fichier `index.html` via le serveur Web de votre c
Ouai je ferais la modif dans ce sens alors

2019-11-13 08:24 UTC, djerfy commented
Le `README.md` est modifié ;) Tu as prévu de pousser l'image aussi sur le Docker Hub ?

2019-11-13 15:45 UTC, 2ec0b4 approved these changes

2019-11-13 15:46 UTC, merged

2019-11-13 15:46 UTC, 2ec0b4 commented
Merci !
Non non, je n'ai pas prévu de pousser l'image sur le Docker Hub