Imitation Karadoc et la vision d'Arthur
2ec0b4/kaamelott-soundboard pull request #70
Opened 2017-11-10 22:11 UTC by FardaleM

2017-11-13 12:28 UTC, Sirgue requested changes
,

2017-11-13 12:28 UTC, Sirgue commented on sounds/sounds.json
> +    }.
`.` à transformer en `,`

2017-11-13 14:36 UTC, FardaleM commented
C’est corrigé.

2017-11-17 22:35 UTC, merged

2017-11-17 22:36 UTC, 2ec0b4 commented
👌🏼
Merci