Eh ben, on est pas sorti du sable !
2ec0b4/kaamelott-soundboard pull request #71
Opened 2017-12-05 15:26 UTC by Zayon

2017-12-05 21:42 UTC, 2ec0b4 requested changes
Peux-tu modifier le son buffet_a_vaisselle.mp3 ? Il contient tout l'épisode 😇
Merci

2017-12-06 08:41 UTC, Zayon commented
C'est maj :)

2017-12-06 21:35 UTC, 2ec0b4 approved these changes

2017-12-06 21:36 UTC, merged

2017-12-06 21:37 UTC, 2ec0b4 commented
Parfait, merci !

http://kaamelott-soundboard.2ec0b4.fr/#son/on_est_pas_sorti_du_sable